### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lakshyalalsharma** [Ahmed067Abdullah/video-calling-app-React-Node#1]
Who I will install it?

**Comment by Ahmed067Abdullah** [comment]
Hi @oppowala, sorry for the late response. Here are the setup instructions

1. Clone the repo and open terminal in the cloned folder
2. Run `npm run install-all` to install the dependencies
3. Run `npm run dev` to run the client and server
4. Open `./client/src/App.js` and paste your localhost IP address and port of server in the `io.connect()` on line 29. 
Eg: `socket.current = io.connect("192.168.xx.xx:5000")`.
You can find your IP address by running `ipconfig` command in the windows terminal and port is hardcoded as 5000 for the localhost.

**Note:** This would only work for clients on your local network. To make it work over internet you would have to deploy your server and update the `io.connect()` accordingly. Also, you would have to use STUN/TURN servers.
